model_configs:
  tokenizer_path: tokenizer
  model_name: t5-base
  path_to_save: 
  model_path: summarizer

training_configs:
  epochs: 20
  batch_size: 30
  eval_batch_size: 2
  reduction_factor: 0.1
  patience: 3
  optimizer: Adam
  weight_decay: 0.0
  shuflle_data: True
  evaluate_dev: True
  use_cuda: True
  betas: [0.9,0.98]
  eps: 0.000000009
  lr : 0.0003
  min_lr: 0.00000001
  fp16: False


data_configs:
  train_path: train_df.csv
  dev_path: test_df.csv
  max_input_len: 600
  max_output_len: 300
  



